name: ncode
description: 'Ncode - Ultra-minimalist Code Editor by Nexora Labs.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  desktop_drop: ^0.5.0
  flutter_riverpod: ^2.6.1
  flutter:
    sdk: flutter

  # Paquete de UI del ecosistema Nexora (Dependencia local)
  nexora_ui:
    path: ../nexora_ui

  # Integración nativa y estado
  flutter_rust_bridge: ^2.12.0
  highlight: ^0.7.0
  shared_preferences: ^2.2.2
  file_picker: ^8.0.0
  xterm: ^3.3.0
  cupertino_icons: ^1.0.8
  code_text_field: ^1.1.0

  # FFI Rust Builder local
  rust_lib_ncode:
    path: rust_builder

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf

    - family: Gliker
      fonts:
        - asset: assets/fonts/Gliker-Regular.ttf
          weight: 700

    - family: Cascadia Code
      fonts:
        - asset: assets/fonts/CascadiaCode-Regular.ttf
