// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<List<FileEntry>> readDirectory({required String dirPath}) =>
    RustLib.instance.api.crateApiFileSystemReadDirectory(dirPath: dirPath);

Future<String> readFileContent({required String filePath}) =>
    RustLib.instance.api.crateApiFileSystemReadFileContent(filePath: filePath);

Future<bool> writeFileContent({
  required String filePath,
  required String content,
}) => RustLib.instance.api.crateApiFileSystemWriteFileContent(
  filePath: filePath,
  content: content,
);

class FileEntry {
  final String name;
  final String path;
  final bool isDir;

  const FileEntry({
    required this.name,
    required this.path,
    required this.isDir,
  });

  @override
  int get hashCode => name.hashCode ^ path.hashCode ^ isDir.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          isDir == other.isDir;
}
