// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<String> getGitBranch({required String repoPath}) =>
    RustLib.instance.api.crateApiGitGetGitBranch(repoPath: repoPath);

Future<List<String>> getGitBranches({required String repoPath}) =>
    RustLib.instance.api.crateApiGitGetGitBranches(repoPath: repoPath);

Future<bool> checkoutGitBranch({
  required String repoPath,
  required String branchName,
}) => RustLib.instance.api.crateApiGitCheckoutGitBranch(
  repoPath: repoPath,
  branchName: branchName,
);

Future<bool> createGitBranch({
  required String repoPath,
  required String newBranchName,
}) => RustLib.instance.api.crateApiGitCreateGitBranch(
  repoPath: repoPath,
  newBranchName: newBranchName,
);

Future<List<GitFileChange>> getGitStatus({required String repoPath}) =>
    RustLib.instance.api.crateApiGitGetGitStatus(repoPath: repoPath);

Future<bool> gitStageFile({
  required String repoPath,
  required String filePath,
}) => RustLib.instance.api.crateApiGitGitStageFile(
  repoPath: repoPath,
  filePath: filePath,
);

Future<bool> gitCommit({required String repoPath, required String message}) =>
    RustLib.instance.api.crateApiGitGitCommit(
      repoPath: repoPath,
      message: message,
    );

Future<String> gitPush({required String repoPath}) =>
    RustLib.instance.api.crateApiGitGitPush(repoPath: repoPath);

Future<String> gitPull({required String repoPath}) =>
    RustLib.instance.api.crateApiGitGitPull(repoPath: repoPath);

class GitFileChange {
  final String path;
  final String status;

  const GitFileChange({required this.path, required this.status});

  @override
  int get hashCode => path.hashCode ^ status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitFileChange &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          status == other.status;
}
