// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Future<List<SearchResultMatch>> searchInWorkspace({
  required SearchOptions options,
}) => RustLib.instance.api.crateApiSearchSearchInWorkspace(options: options);

class SearchOptions {
  final String query;
  final String rootDir;
  final bool isRegex;
  final bool matchCase;
  final bool matchWholeWord;
  final String? fileIncludeFilter;
  final String? fileExcludeFilter;

  const SearchOptions({
    required this.query,
    required this.rootDir,
    required this.isRegex,
    required this.matchCase,
    required this.matchWholeWord,
    this.fileIncludeFilter,
    this.fileExcludeFilter,
  });

  @override
  int get hashCode =>
      query.hashCode ^
      rootDir.hashCode ^
      isRegex.hashCode ^
      matchCase.hashCode ^
      matchWholeWord.hashCode ^
      fileIncludeFilter.hashCode ^
      fileExcludeFilter.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchOptions &&
          runtimeType == other.runtimeType &&
          query == other.query &&
          rootDir == other.rootDir &&
          isRegex == other.isRegex &&
          matchCase == other.matchCase &&
          matchWholeWord == other.matchWholeWord &&
          fileIncludeFilter == other.fileIncludeFilter &&
          fileExcludeFilter == other.fileExcludeFilter;
}

class SearchResultMatch {
  final String filePath;
  final String fileName;
  final BigInt lineNumber;
  final String lineContent;
  final BigInt startCol;
  final BigInt endCol;

  const SearchResultMatch({
    required this.filePath,
    required this.fileName,
    required this.lineNumber,
    required this.lineContent,
    required this.startCol,
    required this.endCol,
  });

  @override
  int get hashCode =>
      filePath.hashCode ^
      fileName.hashCode ^
      lineNumber.hashCode ^
      lineContent.hashCode ^
      startCol.hashCode ^
      endCol.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchResultMatch &&
          runtimeType == other.runtimeType &&
          filePath == other.filePath &&
          fileName == other.fileName &&
          lineNumber == other.lineNumber &&
          lineContent == other.lineContent &&
          startCol == other.startCol &&
          endCol == other.endCol;
}
